---
- name: file upload
  hosts: 114.116.194.17
  connection: local
  tasks:
   file:
   - name: 创建目录
     shell: mkdir -p /data/iot
   - name: upload file.
     copy: src=/data/apache-iotdb-0.9.3-incubating-bin.zip dest=/data/iot
    
