- name: file upload
  hosts: all
  connection: paramiko
  tasks:
   - name: 创建目录
     shell: mkdir -p /data/iot
   - name: upload file.
     copy: src={{path}} dest=/data/iot
   - name: 解压
     shell: cd /data/iot && unzip apache-iotdb-0.9.3-incubating-bin.zip
   - name: 启动iotdb  
     shell: cd /data/iot/apache-iotdb-0.9.3-incubating && nohup sbin/start-server.sh >> nohup.log  2>&1 &
   - name: 查看
     shell: ps aux|grep iotdb
