- name: file upload
  hosts: all
  connection: paramiko
  tasks:
   - name: 创建目录
     shell: mkdir -p /data/iot
   - name: upload file.
     copy: src=/data/apache-iotdb-0.9.3-incubating-bin.zip dest=/data/iot
    
